version: '3.5'

networks:
  tg-auth:
    name: tg-auth
    external: true

services:
  nginx:
    container_name: container_wswalker_nginx
    ports:
      - '8082:80'
      - '8092:443'
    build:
      context: ./container/Nginx
      dockerfile: Dockerfile
    volumes:
      #- ./container/Nginx/Conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./container/Nginx/Conf/server.conf:/etc/nginx/conf.d/server.conf
      - ./container/Nginx/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ../geo/container/certbot/config:/etc/letsencrypt/
    depends_on:
      - wswalker
    networks:
      tg-auth:
        ipv4_address: 192.168.0.43
  wswalker:
    container_name: container_wswalker
    build:
      context: ./container/php8.2.6
    volumes:
      - ./:/var/www/html
    ports:
      - '2346:2346'
    networks:
      tg-auth:
        ipv4_address: 192.168.0.102
    command: php public/index.php start


