version: '3.5'

networks:
  tg-auth:
    name: tg-auth
    external: true

services:
  nginx:
    container_name: container_wswalker_nginx
    ports:
      - '8082:80'
    build:
      context: ./container/Nginx
      dockerfile: Dockerfile
    volumes:
      - ./container/Nginx/Conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wswalker
    networks:
      - tg-auth
  wswalker:
    container_name: container_wswalker
    build:
      context: ./container/php8.2.6
    volumes:
      - ./:/var/www/html
    ports:
      - '2346:2346'
    networks:
      - tg-auth
    command: php public/index.php start


